### PR TITLE
De 887 add is_deleted column

### PR DESCRIPTION
**Pull request by johncgrove**
adding is_active column to avoid hard delete and become soft delete.
This way we can keep track of previous segments and not lose historical data.

We need to make sure refresh is avoided and segment count to return only active segments and make sure its in sync

### CODE REVIEW

**Review by Anton-Shutik — APPROVED** [review]
This looks good as long as we want to deploy it with downtime. We can use another approach and do this in several steps:
1. Add nullable bool column (migration only), deploy&migrate
2. Deploy model field
3. Make the field and database column not nullable

In this case we don't need downtime, but it requires some additional effort

**Review by mvascelli — COMMENTED** [review]
It could be super worth considering whether a more uniquely identifiable field name for soft deletion might be more appropriate here... Especially if we plan to add soft deletion to other tables as well...

Naming it something like `deleted` might be preferable because we already have some tables with `is_active` or `active` fields, and things might get confusing if we end up representing soft deletion with different fields across the repo...

But, with that said, I'm happy we are implementing soft deletion! It's a great problem solver in my opinion

**Comment by johncgrove** [comment]
> It could be super worth considering whether a more uniquely identifiable field name for soft deletion might be more appropriate here... Especially if we plan to add soft deletion to other tables as well...
> 
> Naming it something like `deleted` might be preferable because we already have some tables with `is_active` or `active` fields, and things might get confusing if we end up representing soft deletion with different fields across the repo...
> 
> But, with that said, I'm happy we are implementing soft deletion! It's a great problem solver in my opinion

Ive changed to is_deleted as that is more accurate. i initially thought older file might become active again depending on the slug but looks like the slugs are coming directly from looker, hence i think slug comes directly from the file than the sql hence, once deleted i dont think is likely to become active again! @Anton-Shutik @mvascelli  if you can take a look again that be great

**Review by mvascelli — APPROVED** [review]
It looks great and it's really useful as well!

**Review by lindsayemarc — APPROVED** [review]
with it, i do second Anton's suggestion to use a nullable boolean to sidestep the need for downtime BUT if you are comfy with waiting until maintenance window then i have no qualms with this changeset!

**Comment by lindsayemarc** [comment]
NIT: after looking at the dependent pr in grove (https://github.com/groveco/grove/pull/10014) i am now thinking that it may reduce the smearing of the "is_delete=False" filtering if you add a manager that has a function that looks something like:

```
def active(self):
    return self.exclude(is_deleted=False)
```

**Comment by Anton-Shutik** [comment]
I would still consider multisptep deploy, because we do not shut down workers during maintenance window. That means that any task that uses `Segment` may fail. Also `active()` method would be super handy. It's better to do on queryset rather than on Manager so we can do: `Segments.objects.filter(foo=bar).active()`, but we cannot do that when implemented on manager level. See [ProductQueryset](https://github.com/groveco/grove/blob/master/product/querysets.py) and its usage as example

**Comment by johncgrove** [comment]
@Anton-Shutik @lindsayemarc really like both of your plans! will d some mods on this pr and the other.

**Comment by johncgrove** [comment]
will leave it at hard delete for now since alot of models share cascade, and will require much management.

**Pull request closed without merging**
