### PR TITLE
Optimize segments refreshing

### PR DESCRIPTION
**Pull request by Anton-Shutik**
Optimization. Reduces total redis calls during segment refresh. Uses `sunionstore` instead of iterating over set and adding item one by one.

How do we monitor:
Look at [sentry](https://sentry.io/organizations/grove-collaborative/issues/?project=98837) grove-server project. 
Also we can tail logs
Datadog [avg tasks duration](https://app.datadoghq.com/notebook/160766/segment-refresh-avg-task-duration)

### CODE REVIEW

**Comment by Anton-Shutik** [comment]
@sramirezgroveco I did not. I just replaced `add_segment_membership` and `remove_segment_membership`, since they do 3 redis calls per iteration, while now, we do only 1, preserving same logic

**Comment by sramirezgroveco** [comment]
I'll approve this going out if we can list out how we will monitor for issues in the PR.

**Comment by Anton-Shutik** [comment]
@sramirezgroveco We can watch for avg task duration in datadog https://app.datadoghq.com/notebook/160766/segment-refresh-avg-task-duration

**Comment by sramirezgroveco** [comment]
@Anton-Shutik : That's a great start! Can you add it to the PR description?  I would additionally say we should tail logs and watch for Sentry errors with this change to make sure that we did not unintentionally cause another issue.  If you mark all of that in the PR descrption, I'll approve and we can ship it.

**Comment by Anton-Shutik** [comment]
@sramirezgroveco Added

**Pull request merged**
